version: "3.7"

services:

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./dist/client:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - lambda_functions

  lambda_functions:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment: 
      NODE_ENV: production
    working_dir: /home/app
    restart: always
    command: ["./node_modules/.bin/netlify", "functions:serve", "-p", "8081"]
